----------------
--UA3E
----------------


----------------
--SEGMENT_COEFS
--coefficients as generated by training
----------------
create external table if not exists segment_coefs_hispanic(varstring string, coef double)
row format delimited fields terminated by ','
stored as textfile
location '';
msck repair  table segment_coefs_hispanic;

----------------
--SEGMENT_SCORES
----------------
insert overwrite table segment_scores_hispanic
select uuid, sum(coef)
from ua3e join segment_coefs_hispanic b on ua3e.varstring = b.varstring
group by uuid;
